name: editfoto
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.07.0 <3.0.0'

dependencies: 
  full_screen_image: ^1.0.2
  cupertino_icons: ^1.0.2
  get: 4.6.1
  get_storage: ^2.0.3
  firebase_core: 1.10.6
  firebase_auth: ^3.3.4
  curved_navigation_bar: 1.0.1
  image_cropper: 1.4.1
  image_picker: 0.8.4+4
  firebase_storage: 10.2.4
  cloud_firestore: 3.1.5
  transparent_image: 2.0.0
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_launcher_icons: 0.9.2
  flutter_lints: ^1.0.0
  flutter_test: 
    sdk: flutter

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/icons8-cloud-96.png"

flutter: 
  assets: 
    - assets/images/
    - assets/icons/
  uses-material-design: true

